---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/ubuntu-cf
    tag: 'latest'

inputs:
  - name: ci

run:
  path: ci/ci/tasks/cleanup.sh

params:
  CF_API:
  CF_USERNAME:
  CF_PASSWORD:
  CF_ORG:
  CF_SPACE: