---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/ubuntu-base
    tag: 'latest'

inputs:
  - name: source
  - name: ci
  - name: version

outputs:
  - name: rc

run:
  path: ci/ci/tasks/package.sh

