---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/ubuntu-base
    tag: 'latest'

inputs:
- name: rc-app
- name: rc-manifest
- name: ci

outputs:
- name: artifact

run:
  path: ci/ci/tasks/promote.sh
