---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 'latest'

inputs:
  - name: source
  - name: ci

outputs:
  - name: site

run:
  path: ci/ci/tasks/unit-test.sh

